services:
  django:
    build: ./site
    command: gunicorn polycoid_main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./site/:/usr/src/site/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - postgres_db
    image: ghcr.io/seeeebaaaa/poylcoid-django:latest  # Updated to use GHCR

  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}_prod

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - django
    image: ghcr.io/seeeebaaaa/poylcoid-nginx:latest  # Updated to use GHCR

volumes:
  postgres_data: