services:
  django:
    build: ./site
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./site/:/usr/src/site/
    ports:
      - 8000:8000
    env_file:
      - ./.env

  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
volumes:
  postgres_data: