# Generated by Django 5.0.7 on 2024-11-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmliste', '0003_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='colors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
