name: Build and Push Docker Compose Images to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.SERVER_ENV_PROD }}" > .env

      - name: Copy SSL secrets
        run: |
          touch nginx/polycoid.com_ssl_certificate.crt.pem 
          echo "${{ secrets.POLYCOID_SSL_CERTIFICATE }}" > nginx/polycoid.com_ssl_certificate.crt.pem 
          touch nginx/*.polycoid.com_private_key.key.pem
          echo "${{ secrets.POLYCOID_PRIVATE_KEY }}" > nginx/*.polycoid.com_private_key.key.pem
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Django Image
        run: |
          docker compose -f docker-compose.prod.yml build django
          docker compose -f docker-compose.prod.yml push django

      - name: Build and Push Nginx Image
        run: |
          docker compose -f docker-compose.prod.yml build nginx
          docker compose -f docker-compose.prod.yml push nginx

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/uwu/polycoid
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            touch .env
            echo "${{ secrets.SERVER_ENV_PROD }}" > .env
            export $(grep -v '^#' .env | xargs -d '\n')
            docker compose pull
            docker compose down
            docker compose up -d
