name: Build and Push Docker Compose Images to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.SERVER_ENV_PROD }}" > .env

      - name: Copy SSL secrets
        run: |
          touch ./polycoid.com_ssl_certificate.crt.pem 
          echo "${{ secrets.POLYCOID_SSL_CERTIFICATE }}" > ./polycoid.com_ssl_certificate.crt.pem 
          touch ./*.polycoid.com_private_key.key.pem
          echo "${{ secrets.POLYCOID_PRIVATE_KEY }}" > ./*.polycoid.com_private_key.key.pem
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Django Image
        run: |
          docker compose -f docker-compose.prod.yml build django
          docker compose -f docker-compose.prod.yml push django
      - name: Verify SSL certificates
        run: |
          ls -l ./polycoid.com_ssl_certificate.crt.pem
          ls -l ./*.polycoid.com_private_key.key.pem

      - name: Build and Push Nginx Image
        run: |
          docker compose -f docker-compose.prod.yml build nginx
          docker compose -f docker-compose.prod.yml push nginx
